import { describe, expect, it } from 'vitest';
import { Vector3 } from 'three';
import {
  FluidSystem,
  ParticleSystem,
  PrimitiveSet,
  SimLoop,
  SoftbodySystem,
  createParticleRenderer,
  type ParticleInit,
} from '../../../src/index.js';

/*
 * Fluid → solid mass-ratio monotonicity.
 *
 * Place three soft-body cubes with different inverse masses in a fluid
 * pool, run for ~6 s of simulation time, and verify the equilibrium
 * COM_y ordering matches Archimedes' principle: lighter bodies (higher
 * invMass) settle higher than heavier bodies (lower invMass). This is
 * the regression test for the fluid → solid Newton-3 reaction — without
 * it (or with a wrongly weighted λ denominator) either every body sinks,
 * or every body rockets out, depending on the failure mode.
 *
 * The strict Archimedes-equilibrium assertion (within 5 % of the
 * analytical depth) is a separate concern. This file isolates the
 * monotonicity check, which is the cheaper and more robust signal —
 * absolute equilibrium depth depends on the solid body's effective
 * displaced volume per surface particle (≈ ψ_b / ρ_0), which is in
 * turn sensitive to the boundary-particle sampling pattern; relative
 * ordering is insensitive to that detail.
 *
 * Scene:
 *   - Fluid: spacing 0.025 m, h = 0.05 m, ρ_0 = 1000 kg/m³, 8×10×8 = 640
 *     particles forming a pool. m_fluid = 0.0156 kg, w_fluid =
 *     1/m_fluid = 64.
 *   - Solid: 4×4×4 = 64 particles cube, side L = 0.1 m, starting
 *     submerged mid-column. compliance = 1e-7 (effectively rigid).
 *     Every particle is a surface particle (a fluid boundary).
 *   - Tank: floor + 4 walls (plane colliders), tank bottom at
 *     y = 0, walls at x = ±0.1, z = ±0.1.
 *   - Particle contacts on, so the cube's particles collide with the
 *     fluid particles as well as being pushed by the fluid pressure.
 *   - Settle: 6.0 s of simulation at 60 fps × S = 4 substeps, gravity
 *     (0, -9.81, 0).
 *
 * Mass-ratio sweep — chosen so all three cases FLOAT (ρ_body < ρ_fluid).
 * A neutral or heavy case would sink to the floor regardless of the
 * Δ_density signal, collapsing the COM_y separation we're trying to
 * detect. Three floating ratios stratify by submerged fraction with a
 * clean monotone signal.
 *
 *   - invMass_body = 213 → ρ_body / ρ_fluid ≈ 0.30 (very buoyant)
 *   - invMass_body = 107 → ρ_body / ρ_fluid ≈ 0.60 (moderately buoyant)
 *   - invMass_body =  71 → ρ_body / ρ_fluid ≈ 0.90 (barely buoyant)
 *
 * Equilibrium COM_y per Archimedes for cube side L:
 *   COM_y = y_water + L · (0.5 − ρ_body/ρ_fluid)
 *
 * Observed behaviour: even with the deepest pool that fits in the test
 * budget (10 × 0.025 m), the buoyancy mechanism does not lift the cube
 * to its analytical Archimedes depth within ~6 s of simulation — every
 * cube settles several centimetres below it. The monotonic Newton-3
 * buoyancy signal is nonetheless clear (adjacent COM_y differences of
 * roughly 15–25 mm at t = 6 s). The test asserts the monotonic ORDERING
 * with a 1 mm margin between adjacent ratios — a regression detector for
 * the sign of the Newton-3 reaction, not a quantitative Archimedes match.
 *
 * Why the analytical depth isn't reached: PBF buoyancy is generated by
 * the gravity-induced fluid density gradient acting asymmetrically on
 * the body's neighbour pairs (more fluid pressure below than above,
 * net upward Δp_j on the boundary). The cube is small (4³ particles)
 * and doesn't displace enough fluid above-below to develop the
 * gradient that real Archimedes assumes. Larger bodies (200+ surface
 * particles) accumulate enough paired contributions to float visibly
 * above the floor.
 *
 * Assertion: COM_y(invMass=213) > COM_y(invMass=107) > COM_y(invMass=71).
 */

interface BuildLatticeResult {
  readonly rest: [number, number, number][];
  readonly initial: ParticleInit[];
}

function buildCubeLattice(
  dim: number,
  spacing: number,
  com: [number, number, number],
  invMassBody: number,
): BuildLatticeResult {
  const rest: [number, number, number][] = [];
  const initial: ParticleInit[] = [];
  const half = (dim - 1) / 2;
  for (let iz = 0; iz < dim; iz++) {
    for (let iy = 0; iy < dim; iy++) {
      for (let ix = 0; ix < dim; ix++) {
        const rx = (ix - half) * spacing;
        const ry = (iy - half) * spacing;
        const rz = (iz - half) * spacing;
        rest.push([rx, ry, rz]);
        initial.push({
          position: [rx + com[0], ry + com[1], rz + com[2]],
          invMass: invMassBody,
        });
      }
    }
  }
  return { rest, initial };
}

interface RunSceneArgs {
  readonly invMassBody: number;
  readonly totalSeconds: number;
}

interface RunSceneResult {
  readonly comYFinal: number;
  readonly waterLevel: number;
}

async function runBuoyancyScene(args: RunSceneArgs): Promise<RunSceneResult> {
  const { invMassBody, totalSeconds } = args;

  const renderer = await createParticleRenderer();
  try {
    const spacing = 0.025;
    const h = 2 * spacing;
    const r = spacing * 0.5;
    const restDensity = 1000;

    // Fluid pool — 8×10×8. Depth ≈ 0.25 m — deep enough that a cube
    // placed below the surface has substantial fluid below it (and
    // therefore a meaningful gravity-induced density gradient pushing
    // up on the cube). Shallower pools collapse the buoyancy signal:
    // once the cube reaches the floor, there's no fluid below it, no
    // density gradient, and gravity wins regardless of mass ratio.
    const nx = 8;
    const ny = 10;
    const nz = 8;
    const fluidCount = nx * ny * nz;

    // Solid cube — 4×4×4 = 64. Bigger gives stronger buoyancy
    // differential per ratio (more boundary particles each contributing
    // a ψ_b · W displacement to the fluid density spike); at dim = 3
    // the per-pair reaction is small relative to the contact drag and
    // the cubes barely separate by 1·r at t = 6 s.
    const dim = 4;
    const bodyCount = dim * dim * dim;
    const total = fluidCount + bodyCount;

    // Pool particles cover [−n·s/2, +n·s/2] in xz, [r, r + ny·s] in y.
    // The actual settled water level depends on how the column packs;
    // measured empirically via the column's own settled top particle.
    const initial: ParticleInit[] = [];
    for (let j = 0; j < ny; j++) {
      for (let k = 0; k < nz; k++) {
        for (let i = 0; i < nx; i++) {
          initial.push({
            position: [
              -((nx * spacing) / 2) + spacing * 0.5 + i * spacing,
              spacing * 0.5 + j * spacing,
              -((nz * spacing) / 2) + spacing * 0.5 + k * spacing,
            ],
            // invMass is set by FluidSystem.
          });
        }
      }
    }

    // Solid cube: start ALREADY submerged at a fixed depth, the same
    // for every mass-ratio case, at y = 0.15. The ~0.25 m pool gives
    // ~0.10 m of fluid below the cube and ~0.05 m above — enough fluid
    // below to develop a buoyancy gradient. This isolates the buoyancy
    // mechanism from a drop-and-bounce transient: a cube dropped from
    // above sinks past its equilibrium and, in a shallow pool, reaches
    // the floor before it can rebound.
    const cubeComY = 0.15;
    const cube = buildCubeLattice(dim, spacing, [0, cubeComY, 0], invMassBody);
    initial.push(...cube.initial);

    const particles = new ParticleSystem(renderer, total, r);
    particles.uploadParticles(initial);

    // Tank — floor + 4 walls. Sized to *match* the fluid block's
    // horizontal extent so the column doesn't spread on settle (which
    // would halve the effective water depth and put the cube on the
    // floor for any floating test). Fluid block spans 8·spacing = 0.2 m
    // wide; wall halfX = 0.1 m.
    const tankHalfX = 0.1;
    const tankHalfZ = 0.1;
    const colliders = new PrimitiveSet(particles);
    colliders.addPlane(new Vector3(0, 1, 0), new Vector3(0, 0, 0));
    colliders.addPlane(new Vector3(1, 0, 0), new Vector3(-tankHalfX, 0, 0));
    colliders.addPlane(new Vector3(-1, 0, 0), new Vector3(tankHalfX, 0, 0));
    colliders.addPlane(new Vector3(0, 0, 1), new Vector3(0, 0, -tankHalfZ));
    colliders.addPlane(new Vector3(0, 0, -1), new Vector3(0, 0, tankHalfZ));

    const fluid = new FluidSystem(particles, {
      range: { start: 0, count: fluidCount },
      restDensity,
      smoothingRadius: h,
      particleSpacing: spacing,
      compliance: 1e-4,
    });

    const restFlat = new Float32Array(bodyCount * 3);
    for (let i = 0; i < bodyCount; i++) {
      restFlat[3 * i + 0] = cube.rest[i]![0];
      restFlat[3 * i + 1] = cube.rest[i]![1];
      restFlat[3 * i + 2] = cube.rest[i]![2];
    }
    // Every particle is a surface particle, so every solid particle is a
    // fluid boundary. The body's particles don't collide with each other.
    const softbody = new SoftbodySystem(particles, {
      bodies: [
        {
          range: { start: fluidCount, count: bodyCount },
          restPositions: restFlat,
          surfaceCount: bodyCount,
          compliance: 1e-7, // effectively rigid
        },
      ],
    });

    // Register every solid surface particle as a fluid boundary —
    // dynamic since the cube moves through the water. Must precede
    // SimLoop construction.
    fluid.addBoundary(softbody.surfaceRange(0), { dynamic: true });

    const loop = new SimLoop(particles, {
      substeps: 4,
      iterations: 2,
      gravity: new Vector3(0, -9.81, 0),
      contact: { maxContacts: total * 8 },
      colliders: [colliders],
      materials: [fluid, softbody],
    });

    const dt = 1 / 60;
    const frames = Math.ceil(totalSeconds / dt);
    for (let f = 0; f < frames; f++) {
      await loop.step(dt);
    }

    const snap = await particles.readback();

    // Solid COM_y is the mean y of the cube's particles.
    let comYFinal = 0;
    for (let i = 0; i < bodyCount; i++) {
      comYFinal += snap.positions[4 * (fluidCount + i) + 1]!;
    }
    comYFinal /= bodyCount;

    // Water level: the fluid's top y (max of fluid particles) at end-
    // of-sim. Measured empirically because the rest-density pool height
    // is sensitive to the SPH compression at this scale.
    let waterLevel = -Infinity;
    for (let i = 0; i < fluidCount; i++) {
      const y = snap.positions[4 * i + 1]!;
      if (y > waterLevel) waterLevel = y;
    }

    loop.dispose();
    colliders.dispose();
    particles.dispose();

    return { comYFinal, waterLevel };
  } finally {
    renderer.dispose();
  }
}

describe('fluid → solid mass-ratio monotonicity', () => {
  it('lighter cube settles higher than heavier cube (sweep across invMass = {213, 107, 71})', async () => {
    const totalSeconds = 6.0;

    // Run the three cases sequentially. Each renderer is owned by
    // runBuoyancyScene and disposed at end-of-scope.
    const veryBuoyant = await runBuoyancyScene({
      invMassBody: 213, // ρ_body / ρ_fluid ≈ 0.30
      totalSeconds,
    });
    const moderate = await runBuoyancyScene({
      invMassBody: 107, // ρ_body / ρ_fluid ≈ 0.60
      totalSeconds,
    });
    const barelyBuoyant = await runBuoyancyScene({
      invMassBody: 71, // ρ_body / ρ_fluid ≈ 0.90
      totalSeconds,
    });

    console.info(
      `[fluid-solid-mass-ratio] very-buoyant   invMass=213 (ρ/ρ_0≈0.30)  COM_y=${veryBuoyant.comYFinal.toFixed(4)}  waterLevel=${veryBuoyant.waterLevel.toFixed(4)}`,
    );
    console.info(
      `[fluid-solid-mass-ratio] moderate       invMass=107 (ρ/ρ_0≈0.60)  COM_y=${moderate.comYFinal.toFixed(4)}  waterLevel=${moderate.waterLevel.toFixed(4)}`,
    );
    console.info(
      `[fluid-solid-mass-ratio] barely-buoyant invMass=71  (ρ/ρ_0≈0.90)  COM_y=${barelyBuoyant.comYFinal.toFixed(4)}  waterLevel=${barelyBuoyant.waterLevel.toFixed(4)}`,
    );

    // Ordering: very-buoyant > moderate > barely-buoyant. Margin =
    // 1 mm, well above floating-point noise and well below the
    // separation observed at t = 6 s for these mass ratios. See the
    // file-level comment for why the cubes don't reach their analytical
    // Archimedes depths.
    const margin = 0.001;
    expect(veryBuoyant.comYFinal).toBeGreaterThan(moderate.comYFinal + margin);
    expect(moderate.comYFinal).toBeGreaterThan(barelyBuoyant.comYFinal + margin);

    // End-to-end Newton-3 sign check: the very-buoyant cube must end
    // up STRICTLY HIGHER than the barely-buoyant cube, by at least
    // 3 mm. Catches the failure mode where the kernel produces a
    // sign-correct but vanishingly small reaction (e.g. if a future
    // refactor accidentally drops a factor and the buoyancy
    // collapses to FP noise).
    expect(veryBuoyant.comYFinal - barelyBuoyant.comYFinal).toBeGreaterThan(0.003);
  }, 180_000);
});
