import type { Control, Preset, Values } from '../types.js';
import { buildFluid } from './liquids.js';
import { buildBuoyancy } from './buoyancy.js';
import { buildElastic } from './elastic.js';
import { buildCloth } from './silk.js';
import { buildVortex } from './vortex.js';

const gravity = (value = 9.81): Control => ({
  key: 'gravity',
  label: 'Gravity',
  description: 'Downward acceleration.',
  min: 0,
  max: 15,
  step: 0.1,
  value,
  unit: 'm/s²',
});
const viscosity = (value = 0.06): Control => ({
  key: 'viscosity',
  label: 'Viscosity',
  description: 'How strongly neighboring particles resist flowing past each other.',
  min: 0.005,
  max: 0.3,
  step: 0.005,
  value,
});
const tension = (value = 0.12): Control => ({
  key: 'tension',
  label: 'Surface tension',
  description: 'Pulls the liquid together into smooth drops and sheets.',
  min: 0,
  max: 0.28,
  step: 0.01,
  value,
});
const roughness = (value = 0.1): Control => ({
  key: 'roughness',
  label: 'Surface roughness',
  description: 'Softens highlights on the rendered surface.',
  min: 0.02,
  max: 0.6,
  step: 0.01,
  value,
});

export const presets: readonly Preset[] = [
  {
    id: 'tidal-chamber',
    number: '01',
    name: 'Tidal chamber',
    category: 'FLUID DYNAMICS',
    description:
      'Water spills over low weirs and winds through alternating gaps between taller walls.',
    accent: '#74c9df',
    camera: [2.05, 1.65, 2.8],
    target: [0, 0.35, 0],
    duration: 14,
    controls: [
      gravity(),
      viscosity(),
      tension(),
      {
        key: 'wave',
        label: 'Wave strength',
        description: 'Gently rocks the water from side to side.',
        min: 0,
        max: 3,
        step: 0.1,
        value: 1,
      },
      roughness(),
    ],
    build: (ctx, values) => buildFluid(ctx, values, 'tidal'),
  },
  {
    id: 'crown-impact',
    number: '02',
    name: 'Crown impact',
    category: 'SPLASH & COLLISION',
    description: 'A falling drop splashes into a shallow pool.',
    accent: '#9daaf4',
    camera: [1.85, 1.65, 2.5],
    target: [0, 0.35, 0],
    duration: 9,
    controls: [
      gravity(7),
      viscosity(0.035),
      tension(0.16),
      {
        key: 'height',
        label: 'Drop height',
        description: 'Raises the starting position of the drop.',
        min: 0.65,
        max: 1.4,
        step: 0.05,
        value: 1.1,
        unit: 'm',
        restart: true,
      },
      roughness(0.08),
    ],
    build: (ctx, values) => buildFluid(ctx, values, 'impact'),
  },
  {
    id: 'liquid-marble',
    number: '03',
    name: 'Liquid marble',
    category: 'SURFACE TENSION',
    description:
      'Gravity pulls inward. Click the surface to stretch the liquid and release droplets.',
    accent: '#ccd5e0',
    camera: [1.25, 0.85, 1.65],
    target: [0, 0.5, 0],
    duration: 20,
    controls: [
      {
        ...gravity(2.5),
        label: 'Inward gravity',
        description: 'Attraction toward the center of the drop.',
        max: 8,
      },
      tension(0.12),
      viscosity(0.08),
      {
        key: 'spin',
        label: 'Initial spin',
        description: 'Adds angular motion to the suspended liquid.',
        min: 0,
        max: 2,
        step: 0.1,
        value: 0.5,
        restart: true,
      },
      roughness(0.07),
    ],
    build: (ctx, values) => buildFluid(ctx, values, 'marble'),
  },
  {
    id: 'viscous-pour',
    number: '04',
    name: 'Viscous pour',
    category: 'VISCOSITY',
    description:
      'A continuous ribbon of thick liquid folds into a pool. Adjust viscosity to compare slow folding with free flow.',
    accent: '#eac08e',
    camera: [1.7, 1.5, 2.6],
    target: [0, 0.4, 0],
    duration: 24,
    controls: [
      gravity(4),
      {
        key: 'viscosity',
        label: 'Viscosity',
        description:
          'Implicit diffusion resists shear without becoming unstable at high viscosity.',
        min: 0.01,
        max: 3,
        step: 0.01,
        value: 1.2,
      },
      tension(0.14),
      {
        key: 'flow',
        label: 'Pour rate',
        description: 'Volume supplied by the nozzle.',
        min: 0,
        max: 2,
        step: 0.1,
        value: 1,
      },
      {
        key: 'height',
        label: 'Nozzle height',
        description: 'Raises the nozzle above the pool.',
        min: 0.65,
        max: 1.1,
        step: 0.05,
        value: 1.05,
        unit: 'm',
      },
      roughness(0.12),
    ],
    build: (ctx, values) => buildFluid(ctx, values, 'amber'),
  },
  {
    id: 'buoyancy',
    number: '05',
    name: 'Buoyancy',
    category: 'FLUID & SOLID',
    description:
      'Rubber ducks bob in clear water. Change their density to explore floating and sinking.',
    accent: '#96d7c3',
    camera: [1.95, 1.5, 2.8],
    target: [0, 0.35, 0],
    duration: 15,
    controls: [
      gravity(5),
      {
        key: 'density',
        label: 'Relative density',
        description: 'Object density relative to water. Below 1 floats; above 1 sinks.',
        min: 0.15,
        max: 2,
        step: 0.05,
        value: 0.4,
        restart: true,
      },
      viscosity(0.025),
      tension(0.055),
      roughness(0.055),
    ],
    build: buildBuoyancy,
  },
  {
    id: 'elastic-studies',
    number: '06',
    name: 'Elastic studies',
    category: 'SOFT BODIES',
    description:
      '20 soft forms with holes, curves, and limbs. Moving plates reveal bending, folding, and elastic recovery.',
    accent: '#db9fb2',
    camera: [1.5, 2.2, 3.1],
    target: [0, 0.35, 0],
    duration: 18,
    controls: [
      gravity(6),
      {
        key: 'compression',
        label: 'Compression',
        description: 'How far the plates squeeze the forms. Set to zero to release them.',
        min: 0,
        max: 1,
        step: 0.05,
        value: 0.8,
      },
      {
        key: 'softness',
        label: 'Softness',
        description: 'Allows the forms to compress under their own weight.',
        min: 0,
        max: 1,
        step: 0.05,
        value: 0.9,
        restart: true,
      },
      {
        key: 'height',
        label: 'Release height',
        description: 'Lifts the forms before they drop.',
        min: 0.35,
        max: 1.5,
        step: 0.05,
        value: 0.55,
        unit: 'm',
        restart: true,
      },
    ],
    build: buildElastic,
  },
  {
    id: 'silk-in-motion',
    number: '07',
    name: 'Silk in motion',
    category: 'CLOTH & COLLISION',
    description:
      'A moving sphere pushes through soft red velvet, revealing folds and a grazing-angle sheen.',
    accent: '#cbbde8',
    camera: [1.9, 1.35, 2.7],
    target: [0, 0.85, 0],
    duration: 30,
    controls: [
      {
        key: 'wind',
        label: 'Wind speed',
        description: 'Pushes air across the fabric.',
        min: 0,
        max: 6,
        step: 0.1,
        value: 0.3,
        unit: 'm/s',
      },
      {
        key: 'speed',
        label: 'Sphere speed',
        description: 'Moves the sphere back and forth through the fabric.',
        min: 0.2,
        max: 2,
        step: 0.1,
        value: 0.8,
      },
      {
        key: 'bend',
        label: 'Drape softness',
        description: 'Moves from firm fabric to loose silk. Changes apply immediately.',
        min: 0,
        max: 1,
        step: 0.05,
        value: 0.75,
      },
      gravity(6),
    ],
    build: buildCloth,
  },
  {
    id: 'vortex-plume',
    number: '08',
    name: 'Vortex plume',
    category: 'GAS & ADVECTION',
    description: 'Light scatters through a swirling volume of smoke.',
    accent: '#e7ad87',
    camera: [1.8, 1.3, 2.4],
    target: [0, 0.7, 0],
    duration: 30,
    controls: [
      {
        key: 'swirl',
        label: 'Circulation',
        description: 'Rotational speed of the flow.',
        min: 0,
        max: 4,
        step: 0.1,
        value: 1.8,
      },
      {
        key: 'rise',
        label: 'Updraft',
        description: 'Carries the tracer particles upward.',
        min: 0,
        max: 1,
        step: 0.05,
        value: 0.3,
        unit: 'm/s',
      },
      {
        key: 'emission',
        label: 'Emission rate',
        description: 'Number of new tracer particles per second.',
        min: 100,
        max: 900,
        step: 50,
        value: 500,
        unit: '/s',
      },
      {
        key: 'density',
        label: 'Smoke density',
        description: 'Controls how much light the smoke absorbs and scatters.',
        min: 0.2,
        max: 3,
        step: 0.1,
        value: 1.2,
      },
    ],
    build: buildVortex,
  },
];

export function defaults(preset: Preset): Values {
  return Object.fromEntries(preset.controls.map((control) => [control.key, control.value]));
}
