import type { Control, Preset, Values } from '../types.js';
import { buildFluid } from './liquids.js';
import { buildBodies } from './solids.js';
import { buildCloth } from './silk.js';
import { buildVortex } from './vortex.js';

const gravity = (value = 9.81): Control => ({
  key: 'gravity',
  label: 'Gravity',
  description: 'Downward acceleration.',
  min: 0,
  max: 15,
  step: 0.1,
  value,
  unit: 'm/s²',
});
const viscosity = (value = 0.06): Control => ({
  key: 'viscosity',
  label: 'Viscosity',
  description: 'How strongly neighboring particles resist flowing past each other.',
  min: 0.005,
  max: 0.3,
  step: 0.005,
  value,
});
const tension = (value = 0.12): Control => ({
  key: 'tension',
  label: 'Surface tension',
  description: 'Pulls the liquid together into smooth drops and sheets.',
  min: 0,
  max: 0.28,
  step: 0.01,
  value,
});
const roughness = (value = 0.1): Control => ({
  key: 'roughness',
  label: 'Surface roughness',
  description: 'Softens highlights on the rendered surface.',
  min: 0.02,
  max: 0.6,
  step: 0.01,
  value,
});

export const presets: readonly Preset[] = [
  {
    id: 'tidal-chamber',
    number: '01',
    name: 'Tidal chamber',
    category: 'FLUID DYNAMICS',
    description:
      'A wall of blue water unfolds around a sculpted obstacle. Small forces become sweeping currents.',
    accent: '#74c9df',
    camera: [2.05, 1.65, 2.8],
    target: [0, 0.35, 0],
    duration: 14,
    controls: [
      gravity(),
      viscosity(),
      tension(),
      {
        key: 'wave',
        label: 'Wave strength',
        description: 'Gently rocks the water from side to side.',
        min: 0,
        max: 3,
        step: 0.1,
        value: 1,
      },
      roughness(),
    ],
    build: (ctx, values) => buildFluid(ctx, values, 'tidal'),
  },
  {
    id: 'crown-impact',
    number: '02',
    name: 'Crown impact',
    category: 'SPLASH & COLLISION',
    description:
      'A suspended drop meets a quiet pool. Explore the balance between a crisp splash and a soft landing.',
    accent: '#9daaf4',
    camera: [1.85, 1.65, 2.5],
    target: [0, 0.35, 0],
    duration: 9,
    controls: [
      gravity(7),
      viscosity(0.035),
      tension(0.16),
      {
        key: 'height',
        label: 'Drop height',
        description: 'Raises the starting position of the drop.',
        min: 0.65,
        max: 1.4,
        step: 0.05,
        value: 1.1,
        unit: 'm',
        restart: true,
      },
      roughness(0.08),
    ],
    build: (ctx, values) => buildFluid(ctx, values, 'impact'),
  },
  {
    id: 'liquid-marble',
    number: '03',
    name: 'Liquid marble',
    category: 'SURFACE TENSION',
    description:
      'Liquid suspended in zero gravity. Disturb the sphere and watch its surface pull itself together.',
    accent: '#ccd5e0',
    camera: [1.25, 0.85, 1.65],
    target: [0, 0.5, 0],
    duration: 20,
    controls: [
      tension(0.2),
      viscosity(0.08),
      {
        key: 'spin',
        label: 'Initial spin',
        description: 'Adds angular motion to the suspended liquid.',
        min: 0,
        max: 2,
        step: 0.1,
        value: 0.5,
        restart: true,
      },
      roughness(0.07),
    ],
    build: (ctx, values) => buildFluid(ctx, values, 'marble'),
  },
  {
    id: 'amber-cascade',
    number: '04',
    name: 'Amber cascade',
    category: 'VISCOSITY',
    description:
      'Warm amber liquid folds over ceramic steps. Slow the flow to reveal its changing contours.',
    accent: '#eac08e',
    camera: [1.7, 1.5, 2.6],
    target: [0, 0.4, 0],
    duration: 14,
    controls: [
      gravity(3.5),
      viscosity(0.24),
      tension(0.18),
      {
        key: 'column',
        label: 'Liquid height',
        description: 'Changes the amount of liquid released above the steps.',
        min: 0.65,
        max: 1.1,
        step: 0.05,
        value: 0.9,
        unit: 'm',
        restart: true,
      },
      roughness(0.12),
    ],
    build: (ctx, values) => buildFluid(ctx, values, 'amber'),
  },
  {
    id: 'floating-forms',
    number: '05',
    name: 'Floating forms',
    category: 'FLUID & SOLID',
    description:
      'Three soft forms meet a turquoise pool. Change their weight to explore two-way interaction.',
    accent: '#96d7c3',
    camera: [1.95, 1.5, 2.8],
    target: [0, 0.35, 0],
    duration: 15,
    controls: [
      gravity(5),
      {
        key: 'weight',
        label: 'Body weight',
        description: 'Relative weight of the three objects.',
        min: 0.3,
        max: 3,
        step: 0.1,
        value: 1,
        restart: true,
      },
      viscosity(0.1),
      tension(0.12),
      roughness(0.1),
    ],
    build: (ctx, values) => buildBodies(ctx, values, true),
  },
  {
    id: 'elastic-studies',
    number: '06',
    name: 'Elastic studies',
    category: 'SOFT BODIES',
    description:
      'Sculptural forms land, deform, and settle. Give them a soft touch or a firmer structure.',
    accent: '#db9fb2',
    camera: [1.8, 1.6, 2.8],
    target: [0, 0.55, 0],
    duration: 12,
    controls: [
      gravity(6),
      {
        key: 'softness',
        label: 'Softness',
        description: 'Allows the forms to compress under their own weight.',
        min: 0,
        max: 1,
        step: 0.05,
        value: 0.55,
        restart: true,
      },
      {
        key: 'height',
        label: 'Release height',
        description: 'Lifts the forms before they drop.',
        min: 0.35,
        max: 1.5,
        step: 0.05,
        value: 1,
        unit: 'm',
        restart: true,
      },
    ],
    build: (ctx, values) => buildBodies(ctx, values, false),
  },
  {
    id: 'silk-in-motion',
    number: '07',
    name: 'Silk in motion',
    category: 'CLOTH & WIND',
    description:
      'A fine woven sheet catches a changing breeze. Explore tension, drape, and the rhythm of the wind.',
    accent: '#cbbde8',
    camera: [1.9, 1.35, 2.7],
    target: [0, 0.85, 0],
    duration: 30,
    controls: [
      {
        key: 'wind',
        label: 'Wind speed',
        description: 'Pushes air across the fabric.',
        min: 0,
        max: 6,
        step: 0.1,
        value: 1.2,
        unit: 'm/s',
      },
      {
        key: 'gust',
        label: 'Gust strength',
        description: 'Adds gentle variation to the breeze.',
        min: 0,
        max: 1,
        step: 0.05,
        value: 0.45,
      },
      {
        key: 'bend',
        label: 'Drape softness',
        description: 'Controls resistance to folding.',
        min: 0,
        max: 1,
        step: 0.05,
        value: 0.65,
        restart: true,
      },
      gravity(6),
    ],
    build: buildCloth,
  },
  {
    id: 'vortex-plume',
    number: '08',
    name: 'Vortex plume',
    category: 'GAS & ADVECTION',
    description:
      'Luminous traces reveal an invisible current. Turn up the circulation to draw ribbons through the air.',
    accent: '#e7ad87',
    camera: [1.8, 1.3, 2.4],
    target: [0, 0.7, 0],
    duration: 30,
    controls: [
      {
        key: 'swirl',
        label: 'Circulation',
        description: 'Rotational speed of the flow.',
        min: 0,
        max: 4,
        step: 0.1,
        value: 1.8,
      },
      {
        key: 'rise',
        label: 'Updraft',
        description: 'Carries the tracer particles upward.',
        min: 0,
        max: 1,
        step: 0.05,
        value: 0.3,
        unit: 'm/s',
      },
      {
        key: 'emission',
        label: 'Emission rate',
        description: 'Number of new tracer particles per second.',
        min: 100,
        max: 900,
        step: 50,
        value: 500,
        unit: '/s',
      },
    ],
    build: buildVortex,
  },
];

export function defaults(preset: Preset): Values {
  return Object.fromEntries(preset.controls.map((control) => [control.key, control.value]));
}
